# Usa l'immagine ufficiale e super leggera di NGINX (un server web velocissimo)
FROM nginx:alpine

# Copia tutti i file del sito (HTML, CSS, JS) nella cartella di pubblicazione di NGINX
COPY . /usr/share/nginx/html

# Esponi la porta 80
EXPOSE 80
